// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXOo7MAZTLSJ3gXZjNOE0od4-7-1HfScs',
    appId: '1:326453914816:web:7dff6793ffc873fb291125',
    messagingSenderId: '326453914816',
    projectId: 'dreams-casino-app',
    authDomain: 'dreams-casino-app.firebaseapp.com',
    storageBucket: 'dreams-casino-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuJIO41Av-dxQxYVQhOkoi_AOKJLbmtxY',
    appId: '1:326453914816:android:f9a04e57ae0461e6291125',
    messagingSenderId: '326453914816',
    projectId: 'dreams-casino-app',
    storageBucket: 'dreams-casino-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Qmk5VemGKpILK0wiDyktGAO0EFC21UA',
    appId: '1:326453914816:ios:cf228c2d641293a0291125',
    messagingSenderId: '326453914816',
    projectId: 'dreams-casino-app',
    storageBucket: 'dreams-casino-app.firebasestorage.app',
    iosBundleId: 'com.dreams.fidelizacion',
  );
}
